create table autor
(
    id bigint generated by default as identity,
    nome varchar(255),
    uuid UUID not null,
    primary key (id)
);
create table livro
(
    id bigint generated by default as identity,
    ano integer not null,
    editora varchar(255),
    isbn varchar(255),
    titulo varchar(255),
    uuid UUID not null,
    autor_id bigint,
    primary key (id));

alter table livro add constraint FKrp0atct0grsplospsqqay36vy foreign key (autor_id) references autor;
